### ISSUE TITLE
"Resources" page does not upload files

### ISSUE THREAD

**Issue by ntpimlott** [SENG426-Team/vega-spring#18]
**Description:** 
A logged in admin on the resources page can upload a valid file of an accepted format. An employee or admin is able to see the uploaded resources but only the admin is able to upload files. A user with insufficient privileges will be redirected to the home page.

**Priority:** 
Medium

**Origin:** 
System Testing

**Comment by TyRicard** [comment]
**The actual time spent completing this issue was 35 Story Points.**
